/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "uart.h"
#include <stdio.h>
#include <stdint.h>
#include "osKernel.h"
#include "rom.h"


typedef uint32_t TaskProfiler;
TaskProfiler Task0_Profiler,Task1_Profiler,Task2_Profiler, pTask1_Profiler, pTask2_Profiler;
#define QUANTA 1



static cpu_t &g_cpu;
uint32_t TIM2_Ticks;
static osSemaphore_t sem_step;



void taskCPU(void){
	cpu_reset(&cpu);
	bus_reset();
	term_init();
	term_update_dashboard();
	while(1){
		osSemaphoreWait(&sem_step);
		cpu_step(&g_cpu);
		term_update_dashboard();
	}
}
void taskStepper(void){
	while(1){}
}
void taskIdle(void){
	while(1){

	}
}


int main(void){
	//initialize kernel, and add threads

	uart_tx_init();
	tim2_1hz_interrupt_init();
	osSemaphoreInit(&semaphore1, 1);
	osSemaphoreInit(&semaphore2, 0);
	osKernelInit();
	osKernelAddThreads(&task6502, &task_stepper, &taskIdle);
	osKernelLaunch(QUANTA);

}

void TIM2_IRQHandler(void){

	if (TIM2->SR & SR_UIF) {
	    TIM2->SR &= ~SR_UIF;
	    step_count++; //Create one sem token
	    osSemaphoreSet(&sem_step);   // allow exactly one 6502 instruction
	  }
}

