/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "uart.h"
#include <stdio.h>
#include <stdint.h>
#include "osKernel.h"
#include "rom.h"


typedef uint32_t TaskProfiler;
#define QUANTA 10



uint32_t TIM2_Ticks;


void taskIdle(void){
	while(1){
	}
}


void task6502_1(void) {
	cpu_t *cpu = &tcbs[0].cpu;
	while(1){
	    cpu_step(cpu);
	    if (tcbs[0].state == THREAD_BLOCKED) break;

	}
}

void task6502_2(void) {
	cput_t *cpu = &tcbs[1].cpu;
	while(1){
	    cpu_step(cpu);
	    if (tcbs[0].state == THREAD_BLOCKED) break;

	}
}

int main(void){
	//initialize kernel, and add threads
	uart_tx_init();
	tim2_1hz_interrupt_init();
	osSemaphoreInit(&gpio_lock, 1);
	osSemaphoreInit(&uart_lock, 1);
	osKernelInit();
	osKernelAddThreads(&task6502, &task_stepper, &taskIdle);
	osKernelLaunch(QUANTA);

}

void TIM2_IRQHandler(void){

	if (TIM2->SR & SR_UIF) {
	    TIM2->SR &= ~SR_UIF;
	    step_count++; //Create one sem token
	    osSemaphoreSet(&sem_step);   // allow exactly one 6502 instruction
	  }
}

